version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1828
      POSTGRES_DB: getir_product_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  category-service:
    build:
      context: ./category-service
    ports:
      - "8082:8082"
    image: category-service
    container_name: category-service
    depends_on:
      - db
    env_file:
      - ./category-service/.env

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    image: product-service
    container_name: product-service
    depends_on:
      - db
    env_file:
      - ./product-service/.env

  subcategory-service:
    build:
      context: ./subcategory-service
    ports:
      - "8083:8083"
    image: subcategory-service
    container_name: subcategory-service
    depends_on:
      - db
    env_file:
      - ./subcategory-service/.env

  auth-service:
      build:
        context: ./auth-service
      ports:
        - "8084:8084"
      image: auth-service
      container_name: auth-service
      depends_on:
        - db
      env_file:
        - ./auth-service/.env

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/.env:/.env
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - category-service
      - product-service
      - subcategory-service
      - auth-service

volumes:
  postgres_data:
