server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: category-service
          uri: http://category-service:8082
          predicates:
            - Path=/getir/api/categories/**

        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/getir/api/products/**
